### ISSUE TITLE
[web] - Permitir alteração do menu navbar via arquivo de configuração yaml

### ISSUE THREAD

**Issue by saracamilo** [ecossistema-aurora/regmel#29]
## WHAT

Atualmente, o navbar exibido no sistema utiliza cores e icones fixos,  então precisamos que essas informações possam ser configuradas dinamicamente via o arquivo regmel.yaml

Como atualmente já é feito com o dashboard lateral, veja por exemplo, no arquivo `/config/environment/aurora.regmel.yaml` no trecho entre as linhas 17 e 24:

```yaml
sidebar:
  dashboard:
    title: menu
    items:
      admin_dashboard:
        icon: dashboard
        text: control_panel
        color: text-info
```

isso gera o seguinte resultado:

![Image](https://github.com/user-attachments/assets/8b7b50b4-9f25-4380-b79f-4252d5e163b2)

## CHECKLIST

- [x] Conseguir modificar Icones
- [x] Conseguir modificar textos
- [x] Conseguir modificar ordenação
- [x] Conseguir modificar cores dos icones
